CREATE DATABASE GUFI;
GO

USE GUFI
GO

-- SITUACAO 
CREATE TABLE SITUACAO (
	idSituacao TINYINT PRIMARY KEY IDENTITY,
	descricao VARCHAR(30) NOT NULL
);
GO

-- TIPOUSUARIO
CREATE TABLE TIPOUSUARIO (
	idTipoUsuario TINYINT PRIMARY KEY IDENTITY,
	nomeTipoUsuario VARCHAR(50) NOT NULL UNIQUE
);
GO

-- TIPOEVENTO
CREATE TABLE TIPOEVENTO (
	idTipoEvento SMALLINT PRIMARY KEY IDENTITY,
	nomeTipoEvento VARCHAR(50) NOT NULL UNIQUE
);
GO

-- INSTITUICAO
CREATE TABLE INSTITUICAO (
	idInstituicao SMALLINT PRIMARY KEY IDENTITY,
	nomeFantasia VARCHAR(150) NOT NULL,
	cnpj VARCHAR(18) NOT NULL UNIQUE,
	endereco VARCHAR(150) NOT NULL UNIQUE
);
GO

-- USUARIO
CREATE TABLE USUARIO (
	idUsuario INT PRIMARY KEY IDENTITY,
	idTipoUsuario TINYINT FOREIGN KEY REFERENCES TIPOUSUARIO (idTipoUsuario),
	email VARCHAR(256) NOT NULL UNIQUE,
	senha VARCHAR(20) NOT NULL CHECK (len(senha) >= 8)
);
GO

ALTER TABLE USUARIO
ADD nomeUsuario VARCHAR(80) NOT NULL
GO

-- EVENTO
CREATE TABLE EVENTO (
	idEvento INT PRIMARY KEY IDENTITY,
	idTipoEvento SMALLINT FOREIGN KEY REFERENCES TIPOEVENTO (idTipoEvento),
	idInstituicao SMALLINT FOREIGN KEY REFERENCES INSTITUICAO (idInstituicao),
	nomeEvento VARCHAR(50) NOT NULL,
	descricao VARCHAR(200) NOT NULL,
	dataEvento DATETIME NOT NULL,
	acessoLivre BIT DEFAULT 1
);
GO

-- PRESENCA
CREATE TABLE PRESENCA (
	idPresenca INT PRIMARY KEY IDENTITY,
	idEvento INT FOREIGN KEY REFERENCES EVENTO(idEvento),
	idUsuario INT FOREIGN KEY REFERENCES USUARIO(idUsuario),
	idSituacao TINYINT FOREIGN KEY REFERENCES SITUACAO (idSituacao)
);
GO